#page title
YouKon                                    :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6741169432                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://testflight.apple.com/join/aKAd0AwD # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/apps/testing/com.dcengineer.youkon # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : YouKon                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Unit Conversion and Property Database Managementfor Engineers

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Eliott Radcliffe
your_link                                 : https://www.dc-engineer.com
your_city                                 : Bilbao
email_address                             : Eliott.Radcliffe@dc-engineer.com
linkedin_username                         : www.linkedin.com/in/eliott-radcliffe-dcdc-llc
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           : radcli14
youtube_username                          : https://www.youtube.com/@dc-engineer
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Unit Conversion Made Simple
    description                           : Convert measurements between different unit systems with ease.
    fontawesome_icon_name                 : exchange-alt
    
  - title                                 : Designed for Technical Professionals
    description                           : Perfect for engineers and scientists working with various measurement standards.
    fontawesome_icon_name                 : exchange-alt
    
  - title                                 : Project Organization
    description                           : Group related measurements into projects for better organization and management of your engineering data.
    fontawesome_icon_name                 : folder-open

  - title                                 : Consistent Unit Systems
    description                           : Automatically convert all measurements within a project to a consistent unit system (Imperial or SI) for seamless analysis.
    fontawesome_icon_name                 : balance-scale

  - title                                 : Cross-Platform Support
    description                           : Available on both iOS and Android platforms, ensuring you can access your projects wherever you go.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Material Properties Database
    description                           : Manage and convert material properties including density, elastic, and strength characteristics in one place.
    fontawesome_icon_name                 : database

  - title                                 : Aerospace Applications
    description                           : Specialized support for aerospace vehicle mass properties and dimensions with relevant unit conversions.
    fontawesome_icon_name                 : rocket

  # - title                                 : Recipe Measurements
  #   description                           : Convert cooking measurements between different systems, making recipe scaling and adaptation simple.
  #   fontawesome_icon_name                 : utensils

  # - title                                 : Image Support
  #   description                           : Attach images to your projects for better documentation and reference.
  #   fontawesome_icon_name                 : image

  - title                                 : User-Friendly Interface
    description                           : Clean, intuitive design with quick conversion tools and expandable project tiles for easy navigation.
    fontawesome_icon_name                 : user-check



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
